### ISSUE TITLE
로그인 및 회원가입 구현

### ISSUE THREAD

**Issue by yelynnn** [AdoongE/FE#14]
## ✨ 어떤 기능인가요?

> 카카오톡 로그인 및 회원가입 페이지 구현

## ✅ 작업 상세 내용

1. 온보딩 페이지
- [x] 시작하기, 로그인 버튼 눌렀을 때 로그인 모달 띄우기
- [ ] 온보딩 페이지에서 로고 눌렀을 때, 현재 첫 화면 이동
- [x] 로그인 모달 기능 구현

2. 카카오톡 로그인
- [x] 인가코드 발급 및 백엔드에 넘기는 코드 작성
- [x] 카카오톡 api 연결
- [ ] 백에서 Token 받아서 연결하기

3. 회원가입 페이지
- [x] 회원가입 화면 UI 완성
- [x] 회원가입 api에 입력값 넘기기
- [x] controller, register 이용해서 값 관리
- [x] 항목별 필수사항 및 규칙 걸기
- [ ] 달력 라이브러리 추가
- [ ] 동의하기 내용 추가

**Comment by HeeNamgoong** [comment]
이슈, 브랜치 정리로 close
