### ISSUE TITLE
콘텐츠 생성 이미지, pdf API

### ISSUE THREAD

**Issue by dudwntjs** [AdoongE/FE#42]
## ✨ 어떤 기능인가요?

> 콘텐츠 생성 페이지에서 이미지 및 PDF 파일을 드래그 앤 드롭으로 업로드하고, 백엔드로 전송하는 API를 구현

## ✅ 작업 상세 내용

- [x] 이미지 및 PDF 파일 백엔드 전송 API 개발
- [x] 파일 업로드 UI 디자인 수정 및 개선
- [ ] 프론트엔드에서 업로드된 이미지 확대 보기 기능 추가

**Comment by HeeNamgoong** [comment]
이슈, 브랜치 정리로 close
