### ISSUE TITLE
콘텐츠 상세보기/삭제 기능

### ISSUE THREAD

**Issue by yelynnn** [AdoongE/FE#43]
## ✨ 어떤 기능인가요?

> 콘텐츠 박스에서 상세보기와 콘텐츠 삭제 기능 구현

## ✅ 작업 상세 내용

- [ ] 콘텐츠 조회 api 연결
- [ ] 케밥메뉴 디자인 수정
- [ ] 상세보기 api id랑 연결
- [ ] 삭제하기 기능 구현

**Comment by HeeNamgoong** [comment]
이슈, 브랜치 정리로 close
